# Generated by Django 3.1.5 on 2021-02-17 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_member', to='posts.member'),
        ),
    ]
