# Generated by Django 3.1.5 on 2021-03-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20210307_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
    ]
