# Generated by Django 3.1.5 on 2021-03-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_remove_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='posts.Like'),
        ),
    ]
