# Generated by Django 3.1.5 on 2021-03-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20210307_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='likes', to='posts.Like'),
        ),
    ]
