# Generated by Django 3.1.5 on 2021-03-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20210307_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='likes', to='posts.Like'),
        ),
    ]
