# Generated by Django 3.1.5 on 2021-03-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20210308_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='voters',
        ),
    ]
