# Generated by Django 3.1.5 on 2021-03-08 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0035_post_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='voters',
            field=models.ManyToManyField(related_name='likes_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
