# Generated by Django 3.1.5 on 2021-04-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_auto_20210429_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
