# Generated by Django 3.1.5 on 2021-01-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
