# Generated by Django 3.1.5 on 2021-02-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='sample.jpg', upload_to='users/'),
            preserve_default=False,
        ),
    ]
