# Generated by Django 3.1.5 on 2021-04-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_chat'),
        ('users', '0005_auto_20210330_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projects',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
