# Generated by Django 3.1.5 on 2021-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='api/posts/sample.jpg', null=True, upload_to='users/'),
        ),
    ]
