# Generated by Django 3.1.5 on 2021-05-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210429_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
